#!/bin/bash

clear

# Get current cPanel user name
me=$(whoami)

echo "-- Git hook creator for $me server --"
echo "If dirs already exist, they will be deleted. So, please do it carefully."
echo ""
echo -n "Repo name (without .git suffix): "
read repo_name

# Prepare the repo directory
repo_dir=~/repos/webarq/$repo_name.git
rm -Rf $repo_dir

# Create the repo directory
mkdir $repo_dir

# Init git
cd $repo_dir && git init --bare

# Get the project dir
echo -n "Project (full mode) directory: "
read project_dir
rm -Rf $project_dir

# Create the project directory
mkdir $project_dir

# Prepare the hook file
hook_file=$repo_dir/hooks/post-update

# Create the hook file
touch $hook_file
echo "#!/bin/bash" >> $hook_file
echo "git --work-tree=$project_dir --git-dir=$repo_dir checkout -f" >> $hook_file

# Get additional scripts
echo -n "Post scripts: "
read post_scripts

# Append to hook file
echo $post_scripts >> $hook_file

# Make it executable
chmod +x $hook_file

# Symlink
echo -n "Need to create a symlink? (y/n) "
read to_create_symlink
if [ $to_create_symlink == 'y' ]
  then
    echo -n "Source dir : $project_dir/"
    read symlink_source_dir
    symlink_source_dir="$project_dir/$symlink_source_dir"
    mkdir -p $symlink_source_dir

    target_dir_prefix=/home/$me/public_html/
    echo -n "Target dir: $target_dir_prefix"
    read symlink_target_dir
    symlink_target_dir=$target_dir_prefix$symlink_target_dir

    ln -sf $symlink_source_dir $symlink_target_dir
fi

echo "Done. Your Git remote is ssh://$me@$me.webarq.com:1903$repo_dir."
